### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by ulgens** [hahey/django-migration-vis#10]
@hahey @hartwork Can you please release a new version with the latest changes and submit it to PyPI? Thanks a lot.

**Comment by hartwork** [comment]
2.0.1 just hit PyPI and there is a GitHub release as well:
- https://pypi.org/project/django-migration-vis/2.0.1/
- https://github.com/hahey/django-migration-vis/releases/tag/v2.0.1

Closing as fixed.

**Comment by ulgens** [comment]
Thank you.
